Repository oksimone/cocktellme, pull requests merged in 2020-08, with the labels that each got.

#5 added ajax call to traitify api. Added new js file for contents in traitify api.
  assets/cockTellMeQuestions.js
  questions.html
Labels: enhancement

#7 test
  assets/cocktellme.js
  googleSignIn.html
  welcome.html
Labels: enhancement

#8 new changes
  assets/cocktellme.js
  googleSignIn.html
  questions.html
Labels: enhancement

#12 added new results page.html
  index.html
  results.html
Labels: enhancement

#14 made ID creation. Made a way to save results and test with unique ID.
  assets/cockTellMeQuestions.js
Labels: enhancement

#19 Cleaned code and fixed merge request. added get call to traitfy api.
  assets/cockTellMeQuestions.js
  questions.html
Labels: Javascript Handling

#22 added autoplay to slider with images.
  assets/cocktellme.js
  index.html
Labels: Front End Task, Javascript Handling

#23 added text when user doesn't input text in either email or password field
  assets/cocktellme.js
  assets/googleSignIn.js
  googleSignIn.html
  index.html
Labels: Javascript Handling

#24 added text to images. added speed of carousel play
  assets/cocktellme.js
  index.html
Labels: Front End Task, Javascript Handling, enhancement

#25 cleaned code for slider on index.html
  assets/cocktellme.js
Labels: Front End Task, Javascript Handling, enhancement

#26 new changes to the results.html
  results.html
Labels: Front End Task, enhancement

#28 Updated searchalc page with search buttons
  assets/cocktellme.css
  searchalc.html
Labels: Front End Task, enhancement

#30 added functionality of personality to drink
  README.md
  assets/cockTellMeQuestions.js
  assets/cocktellme.js
  newuser.html
  results.html
Labels: Javascript Handling, enhancement

#31 fixed images being displayed on index.html
  assets/cocktellme.js
Labels: enhancement

#33 new changes
  assets/cocktellme.css
  results.html
Labels: Front End Task

#34 Search JS & HTML Updates
  assets/search.js
  searchalc.html
Labels: Javascript Handling

#35 updated for full github.io
  assets/cockTellMeQuestions.js
  assets/cocktellme.js
  results.html
Labels: Javascript Handling

#36 fixed test
  assets/cockTellMeQuestions.js
Labels: enhancement

#38 fixed button on test completetion
  assets/cockTellMeQuestions.js
  assets/cocktellme.js
  questions.html
Labels: Javascript Handling, enhancement

#41 Created folders for js css and images
  assets/css/cocktellme.css
  assets/images/concrete-texture.png
  assets/images/congruent_outline.png
  assets/images/people-drinking.jpg
  assets/images/topography.png
  assets/js/cockTellMeQuestions.js
  assets/js/cocktellme.js
  assets/js/search.js
  index.html
  newuser.html
  questions.html
  results.html
  searchalc.html
Labels: Front End Task, enhancement

#42 Cosmetic changes to index and new users
  assets/css/cocktellme.css
  newuser.html
Labels: enhancement

#43 fixed button error cleaned code
  README.md
  assets/js/cockTellMeQuestions.js
  assets/js/cocktellme.js
  assets/js/search.js
  index.html
  questions.html
  results.html
  searchalc.html
Labels: Javascript Handling, enhancement
